/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaz;

import Clases.Cliente;
import Gestion.GestorClientes;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class DialogModifyClient extends javax.swing.JDialog {
    GestorClientes GC = Inicio.GC; 
    String cliente;
    /**
     * Creates new form DialogModifyClient
     */
    public DialogModifyClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                
        for (int i = 0; i < GC.size(); i++) {
            ComboClientes.addItem(GC.get(i).getNombreYApellido());
        }
        ComboPropiedades.addItem("cédula");
        ComboPropiedades.addItem("nombre");
        ComboPropiedades.addItem("apellido");
        ComboPropiedades.addItem("teléfono");
        ComboPropiedades.addItem("dirección");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboClientes = new javax.swing.JComboBox<>();
        ComboPropiedades = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Elija el cliente que quiere modificar");

        ComboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes" }));
        ComboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboClientesActionPerformed(evt);
            }
        });

        ComboPropiedades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propiedad" }));
        ComboPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPropiedadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(ComboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(ComboPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboClientesActionPerformed
       cliente = ComboClientes.getSelectedItem().toString();
        
    }//GEN-LAST:event_ComboClientesActionPerformed

    private void ComboPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPropiedadesActionPerformed
        String edicion = JOptionPane.showInputDialog("Introduce tu cambio a " + ComboPropiedades.getSelectedItem());
        for (int i = 0; i < GC.size(); i++) {
            if (cliente.equals(GC.get(i).getNombreYApellido())) {
                if (ComboPropiedades.getSelectedItem().equals("cedula")) {
                    GC.get(i).setCedula(edicion);
                }
                if (ComboPropiedades.getSelectedItem().equals("nombre")) {
                    GC.get(i).setNombre(edicion);
                }
                if (ComboPropiedades.getSelectedItem().equals("apellido")) {
                    GC.get(i).setApellido(edicion);
                }
                if (ComboPropiedades.getSelectedItem().equals("telefono")) {
                    GC.get(i).setTelefono(edicion);
                }
                if (ComboPropiedades.getSelectedItem().equals("dirección")) {
                    GC.get(i).setDirección(edicion);
                }
            }
            JOptionPane.showMessageDialog(null, "Su cliente editado es: " + GC.toString(), "Cliente modificado", HEIGHT);
        }   
    }//GEN-LAST:event_ComboPropiedadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModifyClient dialog = new DialogModifyClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboClientes;
    private javax.swing.JComboBox<String> ComboPropiedades;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
